### ISSUE TITLE
Cloning fails (permissions) when cloning as shown in the Readme

### ISSUE THREAD

**Issue by Kadigan** [dimtass/meta-nanopi-rockchip64#1]
Attempting either `git clone git@bitbucket.org:dimtass/meta-allwinner-hx.git` or `git clone --depth 1 -b dunfell git@github.com:openembedded/meta-openembedded.git` produces

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The solution, obviously, is to replace `git@` with `https://` and correct `:` to `/`.

Maybe not a big issue, but can trip someone up.

**Comment by dimtass** [comment]
I've did the changes in the README file, as there were copy-paste for another project of mine.
